### ISSUE TITLE
Release 2.9.0?

### ISSUE THREAD

**Issue by mikeoconnor0308** [coreweave/tensorizer#116]
Thanks for the library, it's great!

The addition of `n_readers` #87 massively improves the performance, and the README.md refers to the setting. Is there a plan to release 2.9.0 with this feature?

**Comment by wbrown** [comment]
We do plan on releasing it, as soon as we address the performance regressions for the `n_readers==1` case, as there are some HTTP proxy servers that do not properly work with range gets.

**Comment by Eta0** [comment]
Tensorizer v2.9.0 is fully released ([git tag](https://github.com/coreweave/tensorizer/tree/v2.9.0), [PyPI page](https://pypi.org/project/tensorizer/2.9.0)) as of 2024-04-17!
