### ISSUE TITLE
 Is it possible to serialize LoRA adapter bin / safetensors file?

### ISSUE THREAD

**Issue by AAnirudh07** [coreweave/tensorizer#135]
Hello team,
Thank you for your work on the `tensorizer` library. I have a question regarding the serialization capabilities of `tensorizer`. Specifically, is it possible to serialize LoRA adapter bin or safetensors file using `tensorizer`?

**Comment by bchess** [comment]
Hi @AAnirudh07 -

tensorizer has its own unique file format. It is possible to load a `safetensors` file using the normal `transformers` package and then use tensorizer to write it out in the tensorizer format. But tensorizer doesn't natively read or write other file formats. Hope that answers your question.

**Comment by AAnirudh07** [comment]
got it, thank you!
